version: "3.8"

services:
  bot-factory:
    build:
      context: ..
      dockerfile: setup/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../bots:/app/bots
    restart: unless-stopped

    # Лимиты
    mem_limit: 512m
    cpus: 1.0
